### PR TITLE
fix invalid signature when params dict used with = in mp uploadId 

### PR DESCRIPTION
**Pull request by j0hnsmith**

### CODE REVIEW

**Comment by tax** [comment]
Thanks for the pull request, are you able to add a testcase for this?

**Comment by tax** [comment]
Thanks for the pull request! Can you please add a test for this if possible?

**Comment by j0hnsmith** [comment]
Sure

**Comment by j0hnsmith** [comment]
Test added

**Comment by tax** [comment]
thanks a lot! Merged

**Comment by tax** [comment]
bumped version to 0.1.7 and released to pypi, thanks again.

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://rail-logistic.com/till.php?rzuc>

 

info@whywouldwe.com

**Comment by j0hnsmith** [comment]
Hello!

 

New message, please read <http://demo2.martsaurus.com/finished.php?m>

 

info@whywouldwe.com

**Pull request merged**
